### PR TITLE
Run applications from search page

### PR DESCRIPTION
**Pull request by fravaccaro**
A click on the app name will launch the app. Viewing the .desktop file was moved in the long-press menu.

### CODE REVIEW

**Comment by sargo-devel** [comment]
Hi,
When I created APPS section, my first attempt was like yours, but then I decided to make it opposite way.
For two reasons:
1. It is a search app and the default behaviour for touching a search result should be the same for all sections: to show the details.
2. There are some .desktop files that shouldn't be run directly and sometimes it is better to view them first.

But obviously your approach is more convenient in most cases and I propose to make it as an switchable option for those who are brave enough to use it :)
This could be e.g. suboption "* Launch app directly" under "*Enable APPS section" in "Current profile setup".
Would you like to do this?

**Comment by fravaccaro** [comment]
Yes, it makes sense to offer an interface as coherent as possible and I agree the best way to handle different needs would be a toggle in settings - unluckily my coding skills are really limited at the moment, so I'm afraid I can't be useful as I'd like to be :/ I can try to look into that, but I doubt I'll be successful!

**Comment by sargo-devel** [comment]
Ok. I added this option (commit b3bc6e60).
This will be part of a new release soon.

**Comment by sargo-devel** [comment]
It has been published in Jolla Store (2017-07-06)

**Pull request closed without merging**
